name: cloudflare-pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "assets/fonts/SymbolsNerdFontMono-Regular.ttf"
      - "assets/icon/terminal.png"
      - "assets/icon/wakterm-icon.svg"
      - "ci/build-docs.sh"
      - "ci/Dockerfile.docs"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - "mkdocs_macros.py"
      - "wrangler.toml"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "cloudflare-pages-production"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'wakamex/wakterm'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: Install gelatyx
        uses: baptiste0928/cargo-install@v2
        with:
          crate: gelatyx
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Build docs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source $HOME/.cargo/env
          CARDS=true ./ci/build-docs.sh
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npx wrangler@4.69.0 pages deploy gh_pages \
            --branch main \
            --commit-hash "${GITHUB_SHA}" \
            --commit-message "${{ github.event.head_commit.message || github.sha }}"
